apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: opt-125m
        litellm_params:
          model: openai//model-cache
          api_base: http://vllm-cpu.vllm.svc.cluster.local:8000/v1
          api_key: "none"
    litellm_settings:
      drop_params: true
      num_retries: 2
      request_timeout: 120
    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
      store_model_in_db: false
      allow_requests_on_db_unavailable: true