apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: opt-125m
  namespace: kserve
spec:
  predictor:
    serviceAccountName: minio-sa
    model:
      modelFormat:
        name: vllm
      runtime: vllm-cpu-runtime
      storageUri: s3://models/opt-125m