apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"   # after KServe controller is up
spec:
  project: default
  source:
    repoURL: https://github.com/devam1402/cloud-native-llm-platform
    targetRevision: main
    path: platform/kserve
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }
